[project]
name = "box-office-trend"
version = "0.1.0"
description = "Demo project for tracking box office trends"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg2>=2.9.10",
    "rich>=13.9.4",
]
